config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'welcome/index'
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  get '/logout', to:'sessions#destroy'

  get 'customers/:id/allot',to:'customers#allot',as:'allot'
  post 'customers/:id/allocation',to:'customers#allocation',as:'allocation'
  get 'users/:id/my_list',to:'users#mylist',as:'mylist'

  get 'users/:id/all_feedback' ,to:'users#allfeedback',as:'feedbacks'

  get 'users/:id/teams',to: 'users#list' ,as:'teams'
  # post 'users/:id/all_customers',to: 'users#list' ,as: 'query_of_customers'
  get 'users/:id/all_potential_customers',to: 'users#list_potential' ,as: 'potential_teams'
  post 'users/:id/all_potential_customers',to: 'users#list_potential' ,as: 'potential_teams_change'
  get 'users/:id/all_deep_customers',to: 'users#list_deep' ,as: 'deep_teams'
  post 'users/:id/all_deep_customers',to: 'users#list_deep' ,as: 'deep_teams_change'

  post 'users/:id/query_customers',to: 'users#query',as:'do_query'
  post 'users/:id/check_chosen_teams',to: 'users#multi_choice_check',as:'check_box_query'
  get 'users/:id/check_chosen_teams',to: 'users#multi_choicec_check',as:'show_checked_teams'
  get 'users/:id/improve_potential',to: 'users#multi_choice_improve',as:'improve_checked_teams'
  get 'users/:id/degrade_potential',to: 'users#multi_choice_degrade' ,as:'degrade_checked_teams'
  resources :users
  resources :customers do
    resources :feedbacks
    resources :descriptions
  end
  root 'sessions#new'
end

app/models/description.rb
class Description < ApplicationRecord
  belongs_to :customer

  def self.table_name_prefix
    'beary-crm_development.'
  end
end

app/controllers/descriptions_controller.rb
class DescriptionsController < ApplicationController
  def new
    @description = Description.new
  end

  def create
    @customer = Customer.find_by(team_id: params[:customer_id])
    @description = Description.new(description_params)
      @description = @customer.create_description(description_params)
      redirect_to customer_path(@customer.team_id)
  end

  def edit
    @customer = Customer.find_by(team_id: params[:customer_id])
    @description = Description.find_by(customer_id: @customer.id)
  end

  def update
    @customer = Customer.find_by(team_id: params[:customer_id])
    @description = Description.find_by(customer_id: @customer.id)
    @description.update(description_params)
    redirect_to customer_path(@customer.team_id)
  end

  private
  def description_params
    params.require(:description).permit(:field,:scale,:job,:note,:level,:department)
  end
end

app/helpers/descriptions_helper.rb
module DescriptionsHelper
end

app/views/descriptions/edit.erb
<h4>编辑客户描述：</h4>
<%= form_for :description ,url: customer_description_path, method: :patch do |f| %>
    <div class="input-group">
      <p>
        <%= f.label :行业 %><br>
        <%= f.select :field,options_for_select([["互联网","互联网"],["金融","金融"],["教育","教育"]],@description.field) ,class:"group_select"  %>
      </p>

      <p>
        <%= f.label :规模 %><br>
        <%= f.select :scale,options_for_select([["0~50","0~50"],["50~100","50~100"],["100~500","100~500"]], @description.scale)  %>
      </p>

      <p>
        <%= f.label :等级 %><br>
        <%= f.select :level,options_for_select([["A","A"],["B","B"],["C","C"],["D","D"]],@description.level) %>
      </p>

      <p>
        <%= f.label :部门 %><br>
        <%= f.text_area :department %>
      </p>


      <p>
        <%= f.label :岗位 %><br>
        <%= f.text_area :job %>
      </p>

      <p>
        <%= f.label :备注 %><br>
        <%= f.text_area :note %>
      </p>

      <p>
        <%= f.submit "提交",class:"btn btn-sm btn-primary"%>
      </p>
    </div>
    <%=link_to "返回", :back %>
<% end %>

app/views/descriptions/new.erb
<h4>新建客户描述：</h4>
<%= form_for :description ,url: customer_descriptions_path do |f| %>
    <div class="input-group">
      <p>
        <%= f.label :行业 %><br>
        <%= f.select(:field,options_for_select([["互联网","互联网"],["金融","金融"],["教育","教育"]], :selected => params[:field]))  %>
      </p>

      <p>
        <%= f.label :规模 %><br>
        <%= f.select(:scale,options_for_select([["0~50","0~50"],["50~100","50~100"],["100~500","100~500"]], :selected => params[:scale]))  %>
      </p>

      <p>
        <%= f.label :等级 %><br>
        <%= f.select(:level,options_for_select([["A","A"],["B","B"],["C","C"],["D","D"]], :selected => params[:level]))  %>
      </p>

      <p>
        <%= f.label :部门 %><br>
        <%= f.text_area :department %>
      </p>


      <p>
        <%= f.label :岗位 %><br>
        <%= f.text_area :job %>
      </p>

      <p>
        <%= f.label :备注 %><br>
        <%= f.text_area :note %>
      </p>

      <p>
        <%= f.submit "提交",class:"btn btn-sm btn-primary"%>
      </p>
    </div>
    <%=link_to "返回", :back %>
<% end %>