config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'welcome/index'
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  get '/logout', to:'sessions#destroy'

  get 'customers/:id/allot',to:'customers#allot',as:'allot'
  post 'customers/:id/allocation',to:'customers#allocation',as:'allocation'
  get 'users/:id/my_list',to:'users#mylist',as:'mylist'

  get 'users/:id/all_feedback' ,to:'users#allfeedback',as:'feedbacks'

  get 'users/:id/teams',to: 'users#list' ,as:'teams'
  # post 'users/:id/all_customers',to: 'users#list' ,as: 'query_of_customers'
  get 'users/:id/all_potential_customers',to: 'users#list_potential' ,as: 'potential_teams'
  post 'users/:id/all_potential_customers',to: 'users#list_potential' ,as: 'potential_teams_change'
  get 'users/:id/all_deep_customers',to: 'users#list_deep' ,as: 'deep_teams'
  post 'users/:id/all_deep_customers',to: 'users#list_deep' ,as: 'deep_teams_change'

  post 'users/:id/query_customers',to: 'users#query',as:'do_query'
  post 'users/:id/check_chosen_teams',to: 'users#multi_choice_check',as:'check_box_query'
  get 'users/:id/check_chosen_teams',to: 'users#multi_choicec_check',as:'show_checked_teams'
  get 'users/:id/improve_potential',to: 'users#multi_choice_improve',as:'improve_checked_teams'
  get 'users/:id/degrade_potential',to: 'users#multi_choice_degrade' ,as:'degrade_checked_teams'
  resources :users
  resources :customers do
    resources :feedbacks
    resources :descriptions
  end
  root 'sessions#new'
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :customers
  has_many :feedbacks

  self.table_name = "crm_users"

  def self.table_name_prefix
    'beary-crm_development.'
  end

  validates :name,
            :presence => {:message => "> 请输入用户名"},
            :uniqueness => {:message => "> 用户名已存在"},
            on: :create
  validates :password,
            :presence => {:message => "> 密码不能为空"},
            :confirmation => {:message => "> 两次密码不匹配"},
            :length => {:minimum => 6,:message => "> 密码最短为6位数"},
            on: :create
  validates :password_confirmation,
            :presence => {:message => "> 请输入密码验证"},
            on: :create
  validates :email,
            :uniqueness => {:message => ">电子邮箱已被注册"},
            on: :create

  before_save { self.email = email.downcase }
  #validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  #validates :email, presence: true, length: { maximum: 255 },
            #format: { with: VALID_EMAIL_REGEX },
            #uniqueness: { case_sensitive: false }
  has_secure_password


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
    @user = User.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to sessions_new_path
    else
      render 'new'
    end
  end

  def list
    @q = Team.ransack(params[:q])
    @teams = @q.result.includes(customer: :description).page(params[:page]||1).per_page(params[:perpage]||30)
  end

  def list_potential
    @q = Team.ransack(params[:q])
    @teams = @q.result.joins(:customer).includes(customer: :description).where("customers.potential_level=2").page(params[:page]||1).per_page(params[:perpage]||30)
  end


  def list_deep
    @q = Team.ransack(params[:q])
    @teams = @q.result.joins(:customer).includes(customer: :description).where("customers.potential_level=3").page(params[:page]||1).per_page(params[:perpage]||30)
  end

  def multi_choice_check
    if params[:teams].nil?
      #弹出错误
      redirect_to teams_path(current_user.id)
    else
      @checked_teams = Team.find(params[:teams].keys)
      @c = []
      @checked_teams.each do |i|
        @c << i.id
      end
    end
  end

  def get_multichosen_customers
    a = params[:chosen_teams].slice(1, params[:chosen_teams].length-2)
    b = a.split(",")
    i = 0
    @customers = []
    @checked_teams = Team.find(b)
    while i < b.size do
      @customers << Customer.find_or_create_by(team_id: b[i])
      i += 1
    end
    @customers
  end

  def multi_choice_improve
    @customers = get_multichosen_customers
    @already_added_customers = []
    @new_coming_customers = []
    @customers.each do |t|
      if t.potential_level <= params[:potential_level].to_i
        t.potential_level += 1
        t.save
        @new_coming_customers << t
      else
        @already_added_customers << t
      end
    end
  end

  def multi_choice_degrade
    @customers = get_multichosen_customers
    @customers.each do |t|
      t.potential_level -= 1
      t.save
    end
  end

  def mylist
    @user = current_user
    @q = Customer.where("allocator_name = ?", current_user.name).ransack(params[:q])
    @aimCustomers = @q.result.includes(:team).order(alloted_time: :asc).page(params[:page]||1).per_page(params[:perpage]||30)
  end

  def allfeedback
    @q = Feedback.ransack(params[:q])
    @aimFeedback = @q.result.includes(customer: [:team,:users]).order(user_id: :asc,customer_id: :asc,created_at: :desc).page(params[:page]||1).per_page(params[:perpage]||30)
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :email)
  end

  def query_params
    params.require(:description).permit(:level, :field, :scale, :start_date, :end_date, :state)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def decide_AD()
  if(params[:orderType]=="ASC")
    @type = "DESC"
  else
    @type = "ASC"
  end
  end

  def current_params
    return "?order=#{params[:order]}&orderType=#{params[:orderType]}&level=#{params[:level]}&scale=#{params[:scale]}&field=#{params[:field]}&state=#{params[:state]}&start_date=#{params[:start_date]}&end_date=#{params[:end_date]}&per_page=#{params[:per_page]}&page=#{params[:page]}&potential_level=#{params[:potential_level]}"
  end

  def default_params
    return "?order=id&orderType=ASC&page=1&per_page=30&level=0&field=0&scale=0&state=0&start_date=#{Team.first.created.strftime('%Y-%m-%d')}&end_date=#{Date.today}"
  end
end

app/views/users/list.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <meta charset="utf-8">
</head>
<body>
<%= link_to "返回", user_path %>
<h3>所有客户列表</h3>
<%= link_to "潜在客户列表", potential_teams_url(params[:id])+"?potential_level=2" %>
<%= search_form_for @q do |f| %>
    <div class="input-group"><br>
      <p style="display: inline-block">
        <%= f.label :等级 %><br>
        <%= f.select(:customer_description_level_eq, {"*" => "", "A" => "A", "B" => "B", "C" => "C", "D" => "D"}.collect {|c| [c[0], c[1]]}) %>
      </p>
      <p style="display: inline-block">
        <%= f.label :行业 %><br>
        <%= f.select(:customer_description_field_eq, {"*" => "", "互联网" => "互联网", "金融" => "金融", "教育" => "教育"}.collect {|c| [c[0], c[1]]}) %>
      </p>
      <p style="display: inline-block">
        <%= f.label :规模 %><br>
        <%= f.select(:customer_description_scale_eq, {"*" => "", "0~50" => "0~50", "50~100" => "50~100", "100~500" => "100~500"}.collect {|c| [c[0], c[1]]}) %>
      </p>
      <br>
      <p style="display: inline-block">
        <%= f.label :状态 %><br>
        <%= f.select(:customer_alloted_eq, {"*" => "", "已分配" => "true", "未分配" => "false"}.collect {|c| [c[0], c[1]]}) %>
      </p>
      <br>
      <p style="display: inline-block">
        <%= f.label :销售 %><br>
        <%= f.select(:customer_allocator_name_eq, [""] + User.all.collect {|c| [c.name, c.name]}) %>
      </p>
      <br>
      <%= f.label :开始日期 %>
      <%= f.text_field :created_gteq, 'data-behaviour' => 'datepicker data-date-autoclose' %>
      <%= f.label :结束日期 %>
      <%= f.text_field :created_lteq, 'data-behaviour' => 'datepicker data-date-autoclose' %>
      <br>
      <br><%= f.submit "筛选", class: "btn btn-sm btn-primary" %>
      <%= link_to "复原", teams_url(current_user.id) + "?potential_level=1", class: "btn btn-sm btn-primary" %>
    </div>
<% end %>
<br>
<table class="table table-bordered table-hover">
  <thead>
  <tr>
    <th rowspan="2"></th>
    <th rowspan="2">
      <%= sort_link(@q, :name, '用户名') %>
    </th>
    <th rowspan="2" style="min-width:150px;">
      <%= sort_link(@q, :created, '注册时间') %>
    </th>
    <th rowspan="2" style="min-width:150px;">
      <%= sort_link(@q, :customer_alloted, '状态') %>
    </th>
    <th colspan="6">备注</th>
  </tr>
  <tr>
    <th style="min-width:50px;">
      <%= sort_link(@q, :customer_description_level, '等级') %>
    </th>
    <th style="min-width:100px;">
      <%= sort_link(@q, :customer_description_field, '行业') %>
    </th>
    <th>
      <%= sort_link(@q, :customer_description_scale, '规模') %>
    </th>
    <th style="min-width:200px;">部门</th>
    <th style="min-width:200px;">岗位</th>
    <th>评价</th>
  </tr>
  </thead>
  <%= form_for :teams, url: check_box_query_url(current_user.id) + "?potential_level=1" do |t| %>
      <tbody>
      <% @teams.each do |c| %>
          <% if c.customer == nil %>
              <tr>
          <% elsif c.customer.potential_level == 1 %>
              <tr>
          <% elsif c.customer.potential_level == 2 %>
              <tr class="potential">
          <% elsif c.customer.potential_level == 3 %>
              <tr class="deep">
          <% end %>
          <td><%= check_box_tag "teams[#{c.id}]", c.id %></td>
          <td><%= link_to customer_path(c.id) do %><%= c.name %>
            <% end %></td>
          <td><%= c.created.strftime('%Y-%m-%d %H:%M:%S') %></td>
          <% if c.customer!= nil %>
              <% v = c.customer %>
              <% if v.users.exists? %>
                  <td>已分配给<b><%= v.users[0].name %></b></td>
              <% else %>
                  <td><%= link_to allot_path(c.id) do %>待分配
                    <% end %></td>
              <% end %>
              <% if c.customer.description != nil %>
                  <td><%= c.customer.description.level %></td>
                  <td><%= c.customer.description.field %></td>
                  <td><%= c.customer.description.scale %></td>
                  <td><%= c.customer.description.department %></td>
                  <td><%= c.customer.description.job %></td>
                  <td><%= c.customer.description.note %></td>
              <% else %>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
              <% end %>
          <% else %>
              <td><%= link_to allot_path(c.id) do %>待分配
                <% end %></td>
              <td>-</td>
              <td>-</td>
              <td>-</td>
              <td>-</td>
              <td>-</td>
              <td>-</td>
          <% end %>
      <% end %>
      <%= t.submit "多选操作",class:"btn btn-sm btn-primary"%>
  <% end %>
  </tbody>
</table>
<%= will_paginate @teams, renderer: BootstrapPagination::Rails %>

<script type="text/javascript" charset="UTF-8">
    $.fn.datepicker.defaults.format = "yyyy-mm-dd";
    $.fn.datepicker.dates['en'] = {
        days: ["日", "一", "二", "三", "四", "五", "六"],
        daysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        daysMin: ["日", "一", "二", "三", "四", "五", "六"],
        months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        monthsShort: ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"],
        today: "Today",
        clear: "Clear",
        format: "yyyy-mm-dd",
        titleFormat: "mm yyyy",
        weekStart: 0
    };
    $('[data-behaviour~=datepicker]').datepicker({autoclose: true, todayHighlight: true});
</script>

</body>

app/views/users/list_deep.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <meta charset="utf-8">
</head>
<body>
<%= link_to "返回潜在客户列表", potential_teams_url + "?potential_level=2"%>
<%= link_to "返回全部客户列表", teams_url + "?potential_level=1"%>
<h3>深层客户列表</h3>
<%= search_form_for @q ,url:deep_teams_url do |f| %>
    <div class="input-group"><br>
      <p style="display: inline-block">
        <%= f.label :等级 %><br>
        <%= f.select(:customer_description_level_eq, {"*" => "", "A" => "A", "B" => "B", "C" => "C", "D" => "D"}.collect {|c| [c[0], c[1]]}) %>
      </p>
      <p style="display: inline-block">
        <%= f.label :行业 %><br>
        <%= f.select(:customer_description_field_eq, {"*" => "", "互联网" => "互联网", "金融" => "金融", "教育" => "教育"}.collect {|c| [c[0], c[1]]}) %>
      </p>
      <p style="display: inline-block">
        <%= f.label :规模 %><br>
        <%= f.select(:customer_description_scale_eq, {"*" => "", "0~50" => "0~50", "50~100" => "50~100", "100~500" => "100~500"}.collect {|c| [c[0], c[1]]}) %>
      </p>
      <br>
      <p style="display: inline-block">
        <%= f.label :状态 %><br>
        <%= f.select(:customer_alloted_eq, {"*" => "", "已分配" => "true", "未分配" => "false"}.collect {|c| [c[0], c[1]]}) %>
      </p>
      <br>
      <p style="display: inline-block">
        <%= f.label :销售 %><br>
        <%= f.select(:customer_allocator_name_eq, [""] + User.all.collect {|c| [c.name, c.name]}) %>
      </p>
      <br>
      <%= f.label :开始日期 %>
      <%= f.text_field :created_gteq, 'data-behaviour' => 'datepicker data-date-autoclose' %>
      <%= f.label :结束日期 %>
      <%= f.text_field :created_lteq, 'data-behaviour' => 'datepicker data-date-autoclose' %>
      <br>
      <br><%= f.submit "筛选", class: "btn btn-sm btn-primary" %>
      <%= link_to "复原", potential_teams_url(current_user.id) + "?potential_level=2", class: "btn btn-sm btn-primary" %>
    </div>
<% end %>
<br>
<div class="container" style="overflow: scroll;width:1300px">
  <table class="table table-bordered table-hover">
    <thead>
    <tr>
      <th rowspan="2"></th>
      <th rowspan="2">
        <%= sort_link(@q, :name, '用户名') %>
      </th>
      <th rowspan="2" style="min-width:150px;">
        <%= sort_link(@q, :created, '注册时间') %>
      </th>
      <th rowspan="2" style="min-width:150px;">
        <%= sort_link(@q, :customer_alloted, '状态') %>
      </th>
      <th colspan="6">备注</th>
    </tr>
    <tr>
      <th style="min-width:50px;">
        <%= sort_link(@q, :customer_description_level, '等级') %>
      </th>
      <th style="min-width:100px;">
        <%= sort_link(@q, :customer_description_field, '行业') %>
      </th>
      <th>
        <%= sort_link(@q, :customer_description_scale, '规模') %>
      </th>
      <th style="min-width:200px;">部门</th>
      <th style="min-width:200px;">岗位</th>
      <th>评价</th>
    </tr>
    </thead>
    <tbody>
    <%=form_for :teams,url: check_box_query_url(current_user.id)+"?potential_level=3"  do |t|%>
    <% @teams.each do |c| %>
            <tr class="deep">
              <td><%=check_box_tag "teams[#{c.id}]",c.id %></td>
              <td><%= link_to customer_path(c.id) do %><%= c.name %>
                <% end %></td>
              <td><%= c.created.strftime('%Y-%m-%d %H:%M:%S') %></td>
              <% if c.customer!= nil %>
                  <% v = c.customer %>
                  <% if v.users.exists? %>
                      <td>已分配给<b><%= v.users[0].name %></b></td>
                  <% else %>
                      <td><%= link_to allot_path(c.id) do %>待分配
                        <% end %></td>
                  <% end %>
                  <% if c.customer.description != nil %>
                      <td><%= c.customer.description.level %></td>
                      <td><%= c.customer.description.field %></td>
                      <td><%= c.customer.description.scale %></td>
                      <td><%= c.customer.description.department %></td>
                      <td><%= c.customer.description.job %></td>
                      <td><%= c.customer.description.note %></td>
                  <% else %>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                  <% end %>
              <% else %>
                  <td><%= link_to allot_path(c.id) do %>待分配
                    <% end %></td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
              <% end %>
        <% end %>
        <%= submit_tag "多选操作",class:"btn btn-sm btn-primary" %>
    <% end %>
    </tbody>
  </table>
</div>
<%= will_paginate @teams,renderer: BootstrapPagination::Rails %>
</body>

app/views/users/list_potential.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <meta charset="utf-8">
</head>
<body>
<%= link_to "返回全部客户列表", teams_url + "?potential_level=1" %>
<h3>潜在客户列表</h3>
<%= link_to "深层客户列表", deep_teams_url(params[:id]) + "?potential_level=3" %>
<%= search_form_for @q, url: potential_teams_url do |f| %>
    <div class="input-group"><br>
      <p style="display: inline-block">
        <%= f.label :等级 %><br>
        <%= f.select(:customer_description_level_eq, {"*" => "", "A" => "A", "B" => "B", "C" => "C", "D" => "D"}.collect {|c| [c[0], c[1]]}) %>
      </p>
      <p style="display: inline-block">
        <%= f.label :行业 %><br>
        <%= f.select(:customer_description_field_eq, {"*" => "", "互联网" => "互联网", "金融" => "金融", "教育" => "教育"}.collect {|c| [c[0], c[1]]}) %>
      </p>
      <p style="display: inline-block">
        <%= f.label :规模 %><br>
        <%= f.select(:customer_description_scale_eq, {"*" => "", "0~50" => "0~50", "50~100" => "50~100", "100~500" => "100~500"}.collect {|c| [c[0], c[1]]}) %>
      </p>
      <br>
      <p style="display: inline-block">
        <%= f.label :状态 %><br>
        <%= f.select(:customer_alloted_eq, {"*" => "", "已分配" => "true", "未分配" => "false"}.collect {|c| [c[0], c[1]]}) %>
      </p>
      <br>
      <p style="display: inline-block">
        <%= f.label :销售 %><br>
        <%= f.select(:customer_allocator_name_eq, [""] + User.all.collect {|c| [c.name, c.name]}) %>
      </p>
      <br>
      <%= f.label :开始日期 %>
      <%= f.text_field :created_gteq, 'data-behaviour' => 'datepicker data-date-autoclose' %>
      <%= f.label :结束日期 %>
      <%= f.text_field :created_lteq, 'data-behaviour' => 'datepicker data-date-autoclose' %>
      <br>
      <br><%= f.submit "筛选", class: "btn btn-sm btn-primary" %>
      <%= link_to "复原", potential_teams_url(current_user.id) + "?potential_level=2", class: "btn btn-sm btn-primary" %>
    </div>
<% end %>
<br>
<div class="container" style="overflow: scroll;width:1300px">
  <table class="table table-bordered table-hover">
    <thead>
    <tr>
      <th rowspan="2"></th>
      <th rowspan="2">
        <%= sort_link(@q, :name, '用户名') %>
      </th>
      <th rowspan="2" style="min-width:150px;">
        <%= sort_link(@q, :created, '注册时间') %>
      </th>
      <th rowspan="2" style="min-width:150px;">
        <%= sort_link(@q, :customer_alloted, '状态') %>
      </th>
      <th colspan="6">备注</th>
    </tr>
    <tr>
      <th style="min-width:50px;">
        <%= sort_link(@q, :customer_description_level, '等级') %>
      </th>
      <th style="min-width:100px;">
        <%= sort_link(@q, :customer_description_field, '行业') %>
      </th>
      <th>
        <%= sort_link(@q, :customer_description_scale, '规模') %>
      </th>
      <th style="min-width:200px;">部门</th>
      <th style="min-width:200px;">岗位</th>
      <th>评价</th>
    </tr>
    </thead>
    <tbody>
    <%= form_for :teams, url: check_box_query_url(current_user.id)+"?potential_level=2" do |t| %>
        <% @teams.each do |c| %>
            <tr class="potential">
              <td><%= check_box_tag "teams[#{c.id}]", c.id %></td>
              <td><%= link_to customer_path(c.id) do %><%= c.name %>
                <% end %></td>
              <td><%= c.created.strftime('%Y-%m-%d %H:%M:%S') %></td>
              <% if c.customer!= nil %>
                  <% v = c.customer %>
                  <% if v.users.exists? %>
                      <td>已分配给<b><%= v.users[0].name %></b></td>
                  <% else %>
                      <td><%= link_to allot_path(c.id) do %>待分配
                        <% end %></td>
                  <% end %>
                  <% if c.customer.description != nil %>
                      <td><%= c.customer.description.level %></td>
                      <td><%= c.customer.description.field %></td>
                      <td><%= c.customer.description.scale %></td>
                      <td><%= c.customer.description.department %></td>
                      <td><%= c.customer.description.job %></td>
                      <td><%= c.customer.description.note %></td>
                  <% else %>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                  <% end %>
              <% else %>
                  <td><%= link_to allot_path(c.id) do %>待分配
                    <% end %></td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
              <% end %>
        <% end %>
        <%= t.submit "多选操作", class: "btn btn-sm btn-primary" %>
    <% end %>
    </tbody>
  </table>
</div>
<%= will_paginate @teams, renderer: BootstrapPagination::Rails %>

<script type="text/javascript" charset="UTF-8">
    $.fn.datepicker.defaults.format = "yyyy-mm-dd";
    $.fn.datepicker.dates['en'] = {
        days: ["日", "一", "二", "三", "四", "五", "六"],
        daysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        daysMin: ["日", "一", "二", "三", "四", "五", "六"],
        months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        monthsShort: ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"],
        today: "Today",
        clear: "Clear",
        format: "yyyy-mm-dd",
        titleFormat: "mm yyyy",
        weekStart: 0
    };
    $('[data-behaviour~=datepicker]').datepicker({autoclose: true, todayHighlight: true});
</script>

</body>

app/views/users/multi_choice_check.erb
<h3>以下客户被成功选中：</h3>

  <table class="table table-bordered table-hover">
    <thead>
    <tr>
      <th rowspan="2">客户名></th>
      <th rowspan="2" style="min-width:150px;">注册时间</th>
      <th rowspan="2" style="min-width:150px;">状态</th>
      <th colspan="6">备注</th>
    </tr>
    <tr>
      <th style="min-width:50px;">等级</th>
      <th style="min-width:100px;">行业</th>
      <th>规模</th>
      <th style="min-width:200px;">部门</th>
      <th style="min-width:200px;">岗位</th>
      <th>评价</th>
    </tr>
    </thead>
    <tbody>
        <% @checked_teams.each do |c| %>
            <tr>
              <td><%= c.name %></td>
              <td><%= c.created.strftime('%Y-%m-%d %H:%M:%S') %></td>
              <% if c.customer!= nil %>
                  <% v = c.customer %>
                  <% if v.users.exists? %>
                      <td>已分配给<b><%= v.users[0].name %></b></td>
                  <% else %>
                      <td>待分配</td>
                  <% end %>
                  <% if c.customer.description != nil %>
                      <td><%= c.customer.description.level %></td>
                      <td><%= c.customer.description.field %></td>
                      <td><%= c.customer.description.scale %></td>
                      <td><%= c.customer.description.department %></td>
                      <td><%= c.customer.description.job %></td>
                      <td><%= c.customer.description.note %></td>
                  <% else %>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                  <% end %>
              <% else %>
                  <td>待分配</td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
              <% end %>
        <% end %>
    </tbody>
  </table>
<%if params[:potential_level] == "1"%>
    <%= link_to "提升客户潜在等级",improve_checked_teams_url + "?chosen_teams=#{@c}&potential_level=#{params[:potential_level]}",class:"btn btn-md btn-primary"%>
    <%=link_to "返回",teams_url(current_user.id)+"?potential_level=1",class:"btn btn-md btn-primary"%>
<%elsif params[:potential_level]=="2"%>
    <%= link_to "提升客户潜在等级",improve_checked_teams_url + "?chosen_teams=#{@c}&potential_level=#{params[:potential_level]}",class:"btn btn-md btn-primary"%>
    <%= link_to "降低客户潜在等级",degrade_checked_teams_url + "?chosen_teams=#{@c}&potential_level=#{params[:potential_level]}",class:"btn btn-md btn-danger"%><br>
    <%=link_to "返回",potential_teams_url(current_user.id) + "?potential_level=2",class:"btn btn-md btn-primary"%>
<%elsif params[:potential_level]=="3"%>
    <%= link_to "降低客户潜在等级",degrade_checked_teams_url + "?chosen_teams=#{@c}&potential_level=#{params[:potential_level]}",class:"btn btn-md btn-danger"%>
    <%=link_to "返回",deep_teams_url(current_user.id) + "?potential_level=3",class:"btn btn-md btn-primary"%>
<%end%>

app/views/users/show.erb
<h3>你好，<%=@user.name %></h3>




<%=link_to "查看我的客户",mylist_path ,class:"btn btn-md btn-primary"%><br>

<%=link_to "查看所有客户列表",teams_url(current_user.id)+"?potential_level=1" ,class:"btn btn-md btn-primary"%><br>

<%=link_to "查看所有跟进",feedbacks_path ,class:"btn btn-md btn-primary"%><br>


<%=link_to "退出登录",logout_path ,class:"btn btn-md btn-danger"%><br>