config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'welcome/index'
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  get '/logout', to:'sessions#destroy'

  get 'customers/:id/allot',to:'customers#allot',as:'allot'
  post 'customers/:id/allocation',to:'customers#allocation',as:'allocation'
  get 'users/:id/my_list',to:'users#mylist',as:'mylist'

  get 'users/:id/all_feedback' ,to:'users#allfeedback',as:'feedbacks'

  get 'users/:id/teams',to: 'users#list' ,as:'teams'
  # post 'users/:id/all_customers',to: 'users#list' ,as: 'query_of_customers'
  get 'users/:id/all_potential_customers',to: 'users#list_potential' ,as: 'potential_teams'
  post 'users/:id/all_potential_customers',to: 'users#list_potential' ,as: 'potential_teams_change'
  get 'users/:id/all_deep_customers',to: 'users#list_deep' ,as: 'deep_teams'
  post 'users/:id/all_deep_customers',to: 'users#list_deep' ,as: 'deep_teams_change'

  post 'users/:id/query_customers',to: 'users#query',as:'do_query'
  post 'users/:id/check_chosen_teams',to: 'users#multi_choice_check',as:'check_box_query'
  get 'users/:id/check_chosen_teams',to: 'users#multi_choicec_check',as:'show_checked_teams'
  get 'users/:id/improve_potential',to: 'users#multi_choice_improve',as:'improve_checked_teams'
  get 'users/:id/degrade_potential',to: 'users#multi_choice_degrade' ,as:'degrade_checked_teams'
  resources :users
  resources :customers do
    resources :feedbacks
    resources :descriptions
  end
  root 'sessions#new'
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :team
  has_many :feedbacks,dependent: :nullify
  has_and_belongs_to_many :users
  has_one :description

  def self.table_name_prefix
    'beary-crm_development.'
  end

  before_save :default_values
   def default_values
    self.alloted ||= false
     self.potential_level ||= 1
   end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index

  end

  def show
    @team = Team.find(params[:id])
    @users = Account.find_by_sql("SELECT full_name,profile,name,id,mobile,created,email,team_id,role FROM users Where team_id = #{params[:id]} && role = 0;")
    @user = @users[0]
    get_or_create_customer(params[:id])
    @customer = @team.customer

    @feedbacks = @customer.feedbacks.order("created_at DESC")

    @description = @customer.description
  end

  def new
    @customer = Customer.new
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def create

  end

  def update

  end

  def destroy

  end

  def allot
    @user = User.all
    @team = Team.find(params[:id])

    #@user.customers << @customer
  end

  def allocation
    #@team = Team.find(params[:id])
    #@customer = @team.customer
    @customer = get_or_create_customer(params[:id])
    @tempuser = User.new(allot_params)
    @user = User.find_by(name: @tempuser.name)
    if @customer.users.exists?
      redirect_to customer_path
    else
      @user.customers << @customer
      @customer.alloted = true
      @customer.alloted_time = Time.new
      @customer.allocator_name = @user.name
      @customer.save
      redirect_to customer_path
    end
  end

  def get_or_create_customer(a_number)
    @team = Team.find(a_number)
    Customer.find_or_create_by(team_id: @team.id)
  end

  private
  def allot_params
    params.require(:user).permit(:name)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
  def get_or_create_customer(a_number)
    if Customer.find(a_number)
      @customer = Customer.find(a_number)
    else
      @customer = Team.find(a_number)
      @customer.save
    end
  end
end

app/views/customers/allot.erb
<h2>请问您想将<b><%=@team.name %></b>分配给以下哪位销售？</h2>
<%= form_for :user ,url: allocation_path do |f| %>
    <div class="input-group">
      <p>
        <%= f.label :销售 %><br>
        <%= f.select(:name, User.all.collect { |c| [c.name,c.name]}) %>
      </p>

      <%= f.submit "保存" %>
    </div>
<% end %>

app/views/customers/new.erb
<h1>登录成功</h1>

app/views/customers/show.html.erb
<h3><b><%=@team.name %></b>的名片</h3>
<% if @customer.users.exists? %>
    <i><p>已分配给销售：<%=@customer.users[0].name%></p></i>
<%else %>
  <%=link_to "分配销售",allot_path%>
<%end%>
<br>

<h4><b>基本信息：</b></h4>
<ul>
  <li><b>id:</b><%=@team.id %></li>
  <li><b>域名:</b><%=@team.subdomain %>@<%=@team.email_domain %></li>
  <li><b>注册时间:</b><%=@team.created.strftime('%Y-%m-%d %H:%M:%S') %></li>
  <li><b>更新时间:</b><%=@team.updated.strftime('%Y-%m-%d %H:%M:%S') %></li>
  <li><b>描述：</b><i><%=@team.description %></i></li>
</ul>
<br>

<h4><b>联系人信息:</b></h4>
<ul>
  <li><b>账户名:</b><%=@user.name %></li>
  <li><b>注册姓名:</b><%=@user.full_name %></li>
  <li><b>e-mail:</b><%=@user.email %></li>
  <li><b>联系电话:</b><%=@user.mobile %></li>
  <li><b>注册时间:</b><%=@user.created.strftime('%Y-%m-%d %H:%M:%S') %></li>
  <li><b>资料：</b><i><%=@user.profile %></i></li>
</ul>
<br>

<br>
<h4><b>备注信息:</b></h4>
<% if @description %>
<%=link_to "修改备注信息",edit_customer_description_path(@customer.team_id) %>
<br>
<ul>
  <li><b>等级：</b><i><%=@description.level %></i></li>
  <li><b>行业:</b><%=@description.field %></li>
  <li><b>规模:</b><%=@description.scale %></li>
  <li><b>部门:</b><%=@description.department %></li>
  <li><b>岗位:</b><%=@description.job %></li>
  <li><b>备注:</b><%=@description.note %></li>
</ul>
<% else %>
    <%=link_to "添加备注信息",new_customer_description_path(@customer.team_id) %>

<% end %>
<br>
<br>

<h4><b>跟进信息:</b></h4>
<%=link_to "新增跟进",new_customer_feedback_path(@customer.team_id) %><br>
<table class="table table-hover">
  <tr>
    <th>跟进人</th>
    <th>跟进时间</th>
    <th>跟进内容</th>
  </tr>
  <% @feedbacks.each do |c| %>
      <tr>
        <td><%=c.crm_user_name %></td>
        <td><%=c.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
        <td><%=c.feedback_content %></td>
      </tr>
  <% end %>
</table>


<%= link_to "返回" ,:back %>